receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  redis:
    endpoint: "redis:6379"
    collection_interval: 10s
  postgresql:
    endpoint: "db:5432"
    transport: tcp
    username: postgres
    password: ${POSTGRES_PASSWORD}

exporters:
  # This replaces the otlp_http block
  clickhouse:
    endpoint: "tcp://clickhouse:9000?database=default"
    timeout: 10s
    retry_on_failure:
      enabled: true
  debug:
    verbosity: detailed

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

service:
  telemetry:
    logs:
      level: "warn" # This keeps your terminal quiet
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # Tell the pipeline to use the clickhouse exporter
      exporters: [clickhouse, debug]
    metrics:
      receivers: [otlp, redis, postgresql]
      processors: [batch]
      exporters: [clickhouse, debug]
      